name: LAPIS

on: [ push ]

env:
  DOCKER_IMAGE_NAME: ghcr.io/fengelniederhammer/lapis

jobs:

  dockerImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./lapis
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          cache-from: type=gha,scope=lapis-${{ github.ref }}
          cache-to: type=gha,mode=max,scope=lapis-${{ github.ref }}
          push: true
          build-args: |
            VERSION=${{ github.sha }}

