name: LAPIS Docs

on: [push]

env:
  DOCKER_IMAGE_NAME: ghcr.io/fengelniederhammer/lapis-docs

defaults:
  run:
    working-directory: ./lapis-docs

jobs:

  dockerImage:
    name: Build Docs Docker Image And Run E2E Tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./lapis-docs
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          cache-from: type=gha,scope=lapis-docs-${{ github.ref }}
          cache-to: type=gha,mode=max,scope=lapis-docs-${{ github.ref }}
          build-args: |
            VERSION=${{ github.sha }}

